# Generated by Django 4.2.7 on 2023-11-02 17:35

from django.db import migrations, models
import issues.constants


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[("OPN", "OPN"), ("ASG", "ASG"), ("CLS", "CLS")],
                default=issues.constants.Status["OPENED"],
                max_length=3,
            ),
        ),
    ]
